// web-front-end/react-trader/src/components/trade-blotter/TradeBlotter.tsx
import { useEffect, useRef, useState } from 'react';
import { AgGridReact } from 'ag-grid-react';
import type { ColDef, GridApi, GridReadyEvent, GetRowIdParams } from 'ag-grid-community';
import 'ag-grid-community/styles/ag-grid.css';
import 'ag-grid-community/styles/ag-theme-alpine.css';
import type { Account } from '../../models/account.model';
import type { Trade } from '../../models/trade.model';
import { getTrades } from '../../services/position.service';
import { subscribe } from '../../services/trade-feed.service';

export const columnDefs: ColDef[] = [
    {
        headerName: 'SECURITY',
        field: 'security'
    },
    {
        headerName: 'QUANTITY',
        field: 'quantity'
    },
    {
        headerName: 'SIDE',
        field: 'side'
    },
    {
        headerName: 'STATE',
        field: 'state',
        enableCellChangeFlash: true
    }
];

export function getRowId(params: GetRowIdParams<Trade>): string {
    return params.data.id;
}

interface TradeBlotterProps {
    account?: Account;
}

function TradeBlotter({ account }: TradeBlotterProps) {
    const [trades, setTrades] = useState<Trade[]>([]);
    const gridApiRef = useRef<GridApi | null>(null);
    const pendingTradesRef = useRef<Trade[]>([]);
    const isPendingRef = useRef(true);

    useEffect(() => {
        if (!account) {
            return;
        }
        let cancelled = false;
        isPendingRef.current = true;
        getTrades(account.id)
            .then((result) => {
                if (cancelled) {
                    return;
                }
                setTrades(result);
                pendingTradesRef.current.forEach((tradeUpdate) => update(tradeUpdate));
                pendingTradesRef.current = [];
                isPendingRef.current = false;
            })
            .catch((error) => console.error(error));
        const unsubscribe = subscribe(`/accounts/${account.id}/trades`, (data: Trade) => {
            if (isPendingRef.current) {
                pendingTradesRef.current.push(data);
            } else {
                update(data);
            }
        });
        return () => {
            cancelled = true;
            unsubscribe();
        };
    }, [account?.id]);

    const update = (data: Trade) => {
        const gridApi = gridApiRef.current;
        if (!gridApi) {
            return;
        }
        const row = gridApi.getRowNode(data.id);
        if (row) {
            gridApi.applyTransaction({
                update: [Object.assign(row.data, { state: data.state })]
            });
        } else {
            gridApi.applyTransaction({
                add: [{
                    accountid: data.accountid,
                    created: data.created,
                    id: data.id,
                    quantity: data.quantity,
                    security: data.security,
                    side: data.side,
                    state: data.state,
                    updated: data.updated
                }],
                addIndex: 0
            });
        }
    };

    const onGridReady = (params: GridReadyEvent) => {
        gridApiRef.current = params.api;
        params.api.sizeColumnsToFit();
    };

    return (
        <div>
            <h5>Trades</h5>
            <div className="ag-theme-alpine" style={{ width: '100%', height: 350 }}>
                <AgGridReact
                    columnDefs={columnDefs}
                    rowData={trades}
                    onGridReady={onGridReady}
                    getRowId={getRowId}
                    suppressColumnVirtualisation
                />
            </div>
        </div>
    );
}

export default TradeBlotter;

// web-front-end/angular/main/app/trade/trade-blotter/trade-blotter.component.ts
import { ColDef, GridApi, GridReadyEvent, GetRowIdParams } from 'ag-grid-community';
import { Component, Input, OnChanges, OnDestroy, SimpleChanges } from '@angular/core';
import { Account } from 'main/app/model/account.model';
import { PositionService } from 'main/app/service/position.service';
import { Observable } from 'rxjs';
import { Trade } from '../../model/trade.model';
import { TradeFeedService } from 'main/app/service/trade-feed.service';

@Component({
    selector: 'app-trade-blotter',
    templateUrl: 'trade-blotter.component.html'
})
export class TradeBlotterComponent implements OnChanges, OnDestroy {
    trades$: Observable<Trade[]>;
    @Input() account?: Account;
    trades: Trade[] = [];
    gridApi: GridApi;
    pendingTrades: Trade[] = [];
    isPending = true;
    socketUnSubscribeFn: Function;
    columnDefs: ColDef[] = [
        {
            headerName: 'SECURITY',
            field: 'security'
        },
        {
            headerName: 'QUANTITY',
            field: 'quantity'
        },
        {
            headerName: 'SIDE',
            field: 'side'
        },
        {
            headerName: 'STATE',
            field: 'state',
            enableCellChangeFlash: true
        }
    ];

    constructor(private tradeFeed: TradeFeedService, private tradeService: PositionService) { }

    ngOnChanges(change: SimpleChanges) {
        if (change.account?.currentValue && change.account.currentValue !== change.account.previousValue) {
            const accountId = change.account.currentValue.id;
            this.isPending = true;
            this.tradeService.getTrades(accountId).subscribe((trades: Trade[]) => {
                this.trades = trades;
                this.processPendingTrades();
            });
            this.socketUnSubscribeFn?.();
            this.socketUnSubscribeFn = this.tradeFeed.subscribe(`/accounts/${accountId}/trades`, (data: Trade) => {
                console.log('Trade blotter feed...', data);
                this.updateTrades(data);
            });
        }
    }

    onGridReady(params: GridReadyEvent) {
        console.log('trade blotter is ready...');
        this.gridApi = params.api;
        this.gridApi.sizeColumnsToFit();
    }

    getRowId(params: GetRowIdParams<any>):string {
        return  `Trade-${params.data.id}`;
    }

    ngOnDestroy() {
        this.socketUnSubscribeFn?.();
    }

    private processPendingTrades() {
        this.pendingTrades.forEach((tradeUpdate) => this.update(tradeUpdate));
        this.pendingTrades = [];
        this.isPending = false;
    }

    private update(data: Trade) {
        const row = this.gridApi.getRowNode(`Trade-${data.id}`);
        let tradeData;
        if (row) {
            tradeData = {
                update: [Object.assign(row.data, { state: data.state })]
            };
        } else {
            tradeData = {
                add: [{
                    accountid: data.accountid,
                    created: data.created,
                    id: data.id,
                    quantity: data.quantity,
                    security: data.security,
                    side: data.side,
                    state: data.state,
                    updated: data.updated
                }],
                addIndex: 0
            };
        }
        this.gridApi.applyTransaction(tradeData);
    }

    private updateTrades(data: Trade) {
        if (this.isPending) {
            this.pendingTrades.push(data);
        } else {
            this.update(data);
        }
    }
}

<h5>Trades <span class="text-secondary fs-6">({{ visibleCount }})</span></h5>

<ag-grid-angular style="width: 100%; height: 350px;" class="ag-theme-alpine" [columnDefs]="columnDefs"
    [rowData]="trades" (gridReady)="onGridReady($event)" [getRowId]="getRowId"
    [isExternalFilterPresent]="isExternalFilterPresent" [doesExternalFilterPass]="doesExternalFilterPass"
    (modelUpdated)="onModelUpdated($event)">
</ag-grid-angular>
