// web-front-end/react/src/components/trade/PositionBlotter/PositionBlotter.tsx
import React, { useCallback, useEffect, useRef, useState } from 'react';
import { AgGridReact } from 'ag-grid-react';
import {
  ColDef,
  GetRowIdParams,
  GridApi,
  GridReadyEvent,
} from 'ag-grid-community';
import 'ag-grid-community/styles/ag-grid.css';
import 'ag-grid-community/styles/ag-theme-alpine.css';
import { Account, Position } from '../../../models';
import { positionService } from '../../../services/positionService';
import { tradeFeed } from '../../../services/tradeFeed';

// SECTION 6 — Position blotter (ag-grid + live position feed).
export interface PositionBlotterProps {
  account?: Account;
}

const columnDefs: ColDef[] = [
  {
    field: 'security',
    headerName: 'SECURITY',
  },
  {
    headerName: 'QUANTITY',
    field: 'quantity',
    enableCellChangeFlash: true,
  },
];

export const PositionBlotter = ({ account }: PositionBlotterProps) => {
  const [positions, setPositions] = useState<Position[]>([]);
  const gridApiRef = useRef<GridApi | null>(null);
  const pendingRef = useRef(true);
  const pendingBufferRef = useRef<Position[]>([]);

  const apply = useCallback((data: Position) => {
    const api = gridApiRef.current;
    if (!api) {
      return;
    }
    const row = api.getRowNode(`Position-${data.security}`);
    if (row) {
      api.applyTransaction({
        update: [Object.assign(row.data, { quantity: data.quantity })],
      });
    } else {
      api.applyTransaction({
        add: [
          {
            accountid: data.accountid,
            quantity: data.quantity,
            security: data.security,
            updated: data.updated,
          },
        ],
        addIndex: 0,
      });
    }
  }, []);

  useEffect(() => {
    if (!account) {
      return;
    }
    const accountId = account.id;
    pendingRef.current = true;
    pendingBufferRef.current = [];

    positionService
      .getPositions(accountId)
      .then((fetched: Position[]) => {
        setPositions(fetched);
        pendingBufferRef.current.forEach((position) => apply(position));
        pendingBufferRef.current = [];
        pendingRef.current = false;
      })
      .catch(() => {
        pendingRef.current = false;
      });

    const unsubscribe = tradeFeed.subscribe(
      `/accounts/${accountId}/positions`,
      (data: Position) => {
        if (pendingRef.current) {
          pendingBufferRef.current.push(data);
        } else {
          apply(data);
        }
      }
    );

    return () => {
      unsubscribe();
    };
  }, [account, apply]);

  const onGridReady = useCallback((params: GridReadyEvent) => {
    gridApiRef.current = params.api;
  }, []);

  const getRowId = useCallback(
    (params: GetRowIdParams<Position>) => `Position-${params.data.security}`,
    []
  );

  return (
    <>
      <h5>Positions</h5>
      <div
        className="ag-theme-alpine"
        style={{ width: '100%', height: '350px' }}
      >
        <AgGridReact
          columnDefs={columnDefs}
          rowData={positions}
          getRowId={getRowId}
          onGridReady={onGridReady}
        />
      </div>
    </>
  );
};

// web-front-end/angular/main/app/trade/position-blotter/position-blotter.component.ts
import { ColDef, GridApi, GridReadyEvent, GetRowIdParams } from 'ag-grid-community';
import { Component, Input, OnChanges, OnDestroy, SimpleChanges } from '@angular/core';
import { Account } from 'main/app/model/account.model';
import { Position } from 'main/app/model/trade.model';
import { PositionService } from 'main/app/service/position.service';
import { Observable } from 'rxjs';
import { TradeFeedService } from 'main/app/service/trade-feed.service';

@Component({
  selector: 'app-position-blotter',
  templateUrl: './position-blotter.component.html',
  styleUrls: ['./position-blotter.component.scss']
})
export class PositionBlotterComponent implements OnChanges, OnDestroy {
  @Input() account?: Account;
  positions$: Observable<Position[]>;
  positions: any = [];
  gridApi: GridApi;
  pendingPosition: any[] = [];
  isPending = true;
  socketUnSubscribeFn: Function;

  columnDefs: ColDef[] = [
    {
      field: 'security',
      headerName: 'SECURITY'
    },
    {
      headerName: 'QUANTITY',
      field: 'quantity',
      enableCellChangeFlash: true
    }
  ];

  constructor(private tradeService: PositionService,
    private tradeFeed: TradeFeedService) { }

  ngOnChanges(change: SimpleChanges) {
    if (change.account?.currentValue && change.account.currentValue !== change.account.previousValue) {
      const accountId = change.account.currentValue.id;
      this.isPending = true;

      this.tradeService.getPositions(accountId).subscribe((positions: Position[]) => {
        this.positions = positions;
        this.processPendingPositions();
      }, () => {
        this.isPending = false;
      });


      this.socketUnSubscribeFn?.();
      this.socketUnSubscribeFn = this.tradeFeed.subscribe(`/accounts/${accountId}/positions`, (data: any) => {
        console.log('Position blotter feed...', data);
        this.updatePosition(data);
      });
    }
  }

  processPendingPositions() {
    this.pendingPosition.forEach((position) => this.update(position));
    this.pendingPosition = [];
    this.isPending = false;
  }

  updatePosition(data: any) {
    if (this.isPending) {
      this.pendingPosition.push(data);
    } else {
      this.update(data);
    }
  }

  update(data: any) {
    const row = this.gridApi.getRowNode(this.getRowId({ data } as GetRowIdParams<Position>));
    let positionData;
    if (row) {
      positionData = {
        update: [Object.assign(row.data, { quantity: data.quantity })]
      };
    } else {
      positionData = {
        add: [{
          accountid: data.accountid,
          quantity: data.quantity,
          security: data.security,
          updated: data.updated
        }],
        addIndex: 0
      };
    }
    this.gridApi.applyTransaction(positionData);
  }

  onGridReady(params: GridReadyEvent) {
    console.log('position blotter is ready...');
    this.gridApi = params.api;
  }

  getRowId(params: GetRowIdParams<any>):string {
    return `Position-${params.data.security}`;
  }

  ngOnDestroy() {
    this.socketUnSubscribeFn?.();
  }

}
