// web-front-end/react/src/components/PositionBlotter/PositionBlotter.tsx
import React, { useCallback, useEffect, useRef } from 'react';
import { AgGridReact } from 'ag-grid-react';
import {
	ColDef,
	GridApi,
	GridReadyEvent,
	GetRowIdParams,
} from 'ag-grid-community';

import 'ag-grid-community/styles/ag-grid.css';
import 'ag-grid-community/styles/ag-theme-alpine.css';

import { Account, Position } from './types';
import { subscribe } from './tradeFeed';

const positionServiceUrl = `http://${window.location.hostname}:18090`;

const columnDefs: ColDef<Position>[] = [
	{ field: 'security', headerName: 'SECURITY' },
	{ field: 'quantity', headerName: 'QUANTITY', enableCellChangeFlash: true },
];

interface PositionBlotterProps {
	account?: Account;
	/** Convenience alternative to passing a full `account`. */
	accountId?: number;
}

/**
 * Live positions grid for a selected account. Hydrates from the position
 * service, then applies live updates from the trade feed. Faithfully ports
 * position-blotter.component.ts, including the pending-buffer logic for updates
 * that arrive before hydration completes.
 */
export const PositionBlotter: React.FC<PositionBlotterProps> = ({
	account,
	accountId,
}) => {
	const resolvedAccountId = account?.id ?? accountId;

	const gridApiRef = useRef<GridApi<Position> | null>(null);
	const isPendingRef = useRef<boolean>(true);
	const pendingRef = useRef<Position[]>([]);

	const applyUpdate = useCallback((data: Position) => {
		const api = gridApiRef.current;
		if (!api) {
			return;
		}
		const row = api.getRowNode(data.security);
		if (row && row.data) {
			api.applyTransaction({
				update: [Object.assign(row.data, { quantity: data.quantity })],
			});
		} else {
			api.applyTransaction({
				add: [
					{
						accountid: data.accountid,
						quantity: data.quantity,
						security: data.security,
						updated: data.updated,
					},
				],
				addIndex: 0,
			});
		}
	}, []);

	const handleFeed = useCallback(
		(data: Position) => {
			if (isPendingRef.current) {
				pendingRef.current.push(data);
			} else {
				applyUpdate(data);
			}
		},
		[applyUpdate],
	);

	useEffect(() => {
		if (resolvedAccountId === undefined || resolvedAccountId === null) {
			return;
		}

		let cancelled = false;
		isPendingRef.current = true;
		pendingRef.current = [];

		const hydrate = async () => {
			try {
				const response = await fetch(
					`${positionServiceUrl}/positions/${resolvedAccountId}`,
				);
				if (cancelled) {
					return;
				}
				const positions: Position[] = response.ok
					? await response.json()
					: [];
				gridApiRef.current?.setRowData(positions);
				pendingRef.current.forEach((p) => applyUpdate(p));
				pendingRef.current = [];
				isPendingRef.current = false;
			} catch {
				isPendingRef.current = false;
			}
		};

		hydrate();

		const unsubscribe = subscribe(
			`/accounts/${resolvedAccountId}/positions`,
			handleFeed,
		);

		return () => {
			cancelled = true;
			unsubscribe();
		};
	}, [resolvedAccountId, applyUpdate, handleFeed]);

	const onGridReady = useCallback(
		(params: GridReadyEvent<Position>) => {
			gridApiRef.current = params.api;
		},
		[],
	);

	const getRowId = useCallback(
		(params: GetRowIdParams<Position>) => params.data.security,
		[],
	);

	return (
		<div
			className="ag-theme-alpine"
			style={{ height: '100%', width: '100%' }}
		>
			<AgGridReact<Position>
				columnDefs={columnDefs}
				onGridReady={onGridReady}
				getRowId={getRowId}
			/>
		</div>
	);
};

export default PositionBlotter;

// web-front-end/angular/main/app/trade/position-blotter/position-blotter.component.ts
import { ColDef, GridApi, GridReadyEvent, GetRowIdParams } from 'ag-grid-community';
import { Component, Input, OnChanges, OnDestroy, SimpleChanges } from '@angular/core';
import { Account } from 'main/app/model/account.model';
import { Position } from 'main/app/model/trade.model';
import { PositionService } from 'main/app/service/position.service';
import { Observable } from 'rxjs';
import { TradeFeedService } from 'main/app/service/trade-feed.service';

@Component({
  selector: 'app-position-blotter',
  templateUrl: './position-blotter.component.html',
  styleUrls: ['./position-blotter.component.scss']
})
export class PositionBlotterComponent implements OnChanges, OnDestroy {
  @Input() account?: Account;
  positions$: Observable<Position[]>;
  positions: any = [];
  gridApi: GridApi;
  pendingPosition: any[] = [];
  isPending = true;
  socketUnSubscribeFn: Function;

  columnDefs: ColDef[] = [
    {
      field: 'security',
      headerName: 'SECURITY'
    },
    {
      headerName: 'QUANTITY',
      field: 'quantity',
      enableCellChangeFlash: true
    }
  ];

  constructor(private tradeService: PositionService,
    private tradeFeed: TradeFeedService) { }

  ngOnChanges(change: SimpleChanges) {
    if (change.account?.currentValue && change.account.currentValue !== change.account.previousValue) {
      const accountId = change.account.currentValue.id;
      this.isPending = true;

      this.tradeService.getPositions(accountId).subscribe((positions: Position[]) => {
        this.positions = positions;
        this.processPendingPositions();
      }, () => {
        this.isPending = false;
      });


      this.socketUnSubscribeFn?.();
      this.socketUnSubscribeFn = this.tradeFeed.subscribe(`/accounts/${accountId}/positions`, (data: any) => {
        console.log('Position blotter feed...', data);
        this.updatePosition(data);
      });
    }
  }

  processPendingPositions() {
    this.pendingPosition.forEach((position) => this.update(position));
    this.pendingPosition = [];
    this.isPending = false;
  }

  updatePosition(data: any) {
    if (this.isPending) {
      this.pendingPosition.push(data);
    } else {
      this.update(data);
    }
  }

  update(data: any) {
    const row = this.gridApi.getRowNode(this.getRowId({ data } as GetRowIdParams<Position>));
    let positionData;
    if (row) {
      positionData = {
        update: [Object.assign(row.data, { quantity: data.quantity })]
      };
    } else {
      positionData = {
        add: [{
          accountid: data.accountid,
          quantity: data.quantity,
          security: data.security,
          updated: data.updated
        }],
        addIndex: 0
      };
    }
    this.gridApi.applyTransaction(positionData);
  }

  onGridReady(params: GridReadyEvent) {
    console.log('position blotter is ready...');
    this.gridApi = params.api;
  }

  getRowId(params: GetRowIdParams<any>):string {
    return `Position-${params.data.security}`;
  }

  ngOnDestroy() {
    this.socketUnSubscribeFn?.();
  }

}
