// web-front-end/react-trader/src/components/Dropdown.tsx
import { useId, useState } from 'react';

interface DropdownProps<T> {
  items: T[];
  itemKey?: string;
  selectedItem?: T;
  selectionComparator?: (src: T | undefined, target: T) => boolean;
  onSelectedItemChange?: (item: T) => void;
  placeholder?: string;
}

const defaultComparator = (src: unknown, target: unknown) => src === target;

function Dropdown<T extends Record<string, any>>({
  items,
  itemKey = 'label',
  selectedItem,
  selectionComparator = defaultComparator,
  onSelectedItemChange,
  placeholder = 'Please select an item'
}: DropdownProps<T>) {
  const uid = useId();
  const drpId = `drp${uid}`;
  const drpBtnId = `drpbtn${uid}`;
  const [open, setOpen] = useState(false);

  const onItemClick = (item: T) => {
    setOpen(false);
    if (!selectionComparator(selectedItem, item)) {
      onSelectedItemChange?.(item);
    }
  };

  return (
    <div className="btn-group">
      <button
        id={drpBtnId}
        type="button"
        className="btn btn-sm btn-primary dropdown-toggle"
        aria-controls={drpId}
        aria-expanded={open}
        onClick={() => setOpen((prev) => !prev)}
      >
        {selectedItem?.[itemKey] || placeholder} <span className="caret"></span>
      </button>
      <ul
        id={drpId}
        className={`dropdown-menu${open ? ' show' : ''}`}
        role="menu"
        aria-labelledby={drpBtnId}
      >
        {items.map((item, index) => (
          <li role="menuitem" key={index} onClick={() => onItemClick(item)}>
            <a className={`dropdown-item${selectionComparator(selectedItem, item) ? ' active' : ''}`}>
              {item[itemKey]}
            </a>
          </li>
        ))}
      </ul>
    </div>
  );
}

export default Dropdown;

// web-front-end/angular/main/app/dropdown/dropdown.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from "@angular/core";

let id = 0;

@Component({
    selector: 'app-ngx-dropdown',
    templateUrl: './dropdown.component.html',
    standalone: true
})
export class DropdownComponent implements OnInit {
    @Input() items: any[];
    @Input() itemKey: string = 'label';
    @Input() selectedItem: any;
    @Input() selectionComparator: (src: any, target: any) => boolean;
    @Output() selectedItemChange = new EventEmitter();
    @Input() placeholder: string = "Please select an item";
    drpId: string;
    drpBtnId: string;

    ngOnInit() {
        this.selectionComparator = this.selectionComparator || this.defaultComparator;
        const uid = id++;
        this.drpId = 'drp' + uid;
        this.drpBtnId = 'drpbtn' + uid;
    }

    defaultComparator = (src: any, target: any) => src === target;

    onItemClick(item: any) {
        if (!this.selectionComparator(this.selectedItem, item)) {
            this.selectedItemChange.emit(item);
        }
    }
}

<div class="btn-group" dropdown>
    <button [id]="drpBtnId" dropdownToggle type="button" class="btn btn-sm btn-primary dropdown-toggle" [attr.aria-controls]="drpId" data-test="dropdown-toggle">
        {{ selectedItem?.[itemKey] || placeholder  }} <span class="caret"></span>
    </button>
    <ul [id]="drpId" *dropdownMenu class="dropdown-menu" role="menu" [attr.aria-labelledby]="drpBtnId">
        <li role="menuitem" *ngFor="let item of items" (click)="onItemClick(item)" data-test="dropdown-item" [attr.data-test-value]="item[itemKey]">
            <a class="dropdown-item" [ngClass]="selectionComparator(selectedItem, item) ? 'active' : ''">{{ item[itemKey] }}</a>
        </li>
    </ul>
</div>
