// web-front-end/angular/main/app/trade/trade-ticket/trade-ticket.component.ts
import { Component, Input, Output, EventEmitter, OnInit } from '@angular/core';
import { TradeTicket } from 'main/app/model/trade.model';
import { Stock } from 'main/app/model/symbol.model';
import { Account } from 'main/app/model/account.model';
import { TypeaheadMatch } from 'ngx-bootstrap/typeahead';

@Component({
  selector: 'app-trade-ticket',
  templateUrl: './trade-ticket.component.html',
  styleUrls: ['./trade-ticket.component.scss']
})
export class TradeTicketComponent implements OnInit {

  @Input() stocks: Stock[];
  @Input() account: Account | undefined;
  @Input() rejectionMessage: string | undefined;

  @Output() create = new EventEmitter<TradeTicket>();
  @Output() cancel = new EventEmitter();

  selectedCompany?: string = undefined;
  ticket: TradeTicket;
  filteredStocks: Stock[] = [];

  ngOnInit() {
    this.ticket = {
      quantity: 0,
      accountId: this.account?.id || 0,
      side: 'Buy',
      security: ''
    };

    this.filteredStocks = this.stocks;
  }


  onSelect(e: TypeaheadMatch): void {
    console.log('Selected value: ', e.value);
    this.ticket.security = e.item.ticker;
  }

  onBlur(): void {
    if (this.selectedCompany) return;
    this.ticket.security = '';
  }

  onCreate() {
    if (!this.ticket.security || !this.ticket.quantity) {
      console.warn('Either security is not selected or quanity is not set!')
      return;
    }
    console.log('create tradeTicket', this.ticket);
    this.create.emit(this.ticket);
  }

  onCancel() {
    this.cancel.emit();
  }
}

<div class="p-4">
    <div class="mb-3 row">
        <label class="col-sm-2 col-form-label me-3">Account</label>
        <div class="col-sm-8">
            <input readonly disabled class="form-control" id="accountLabel" [value]="account?.displayName" />
        </div>
    </div>
    <div class="mb-3 row">
        <label class="col-sm-2 col-form-label me-3">Security</label>
        <div class="col-sm-8">
            <input
                id="stock-input"
                [minLength]="1"
                [(ngModel)]="selectedCompany"
                [typeahead]="filteredStocks"
                typeaheadOptionField="companyName"
                (typeaheadOnSelect)="onSelect($event)"
                (blur)="onBlur()"
                placeholder="Search security"
                class="form-control"
            />
        </div>
    </div>

    <div class="mb-3 row">
        <label class="col-sm-2 col-form-label me-3">Side</label>
        <div class="col-sm-8">
            <div class="btn-group">
                <input
                    type="radio"
                    class="btn-check"
                    name="sideButton"
                    value="Buy"
                    id="buyButton"
                    [(ngModel)]="ticket.side"
                    checked
                    #buyButton
                />
                <label class="btn" [ngClass]="buyButton.checked ? 'btn-info btn-sm' : 'btn-secondary btn-sm'" for="buyButton">Buy</label>

                <input
                    type="radio"
                    class="btn-check"
                    name="sideButton"
                    value="Sell"
                    id="sellButton"
                    [(ngModel)]="ticket.side"
                    #sellButton
                />
                <label class="btn" [ngClass]="sellButton.checked ? 'btn-warning btn-sm' : 'btn-secondary btn-sm'" for="sellButton"
                    >Sell</label
                >
            </div>
        </div>
    </div>
    <div class="mb-3 row">
        <label class="col-sm-2 col-form-label me-3">Quantity</label>
        <div class="col-sm-8">
            <input class="form-control d-inline-block" id="quantityField" type="number" [(ngModel)]="ticket.quantity" />
        </div>
    </div>
    <div class="mb-3 row" *ngIf="rejectionMessage">
        <div class="alert alert-danger py-2 rejection-message" id="rejectionMessage" role="alert">{{ rejectionMessage }}</div>
    </div>
    <div class="mb-3 row">
        <button class="btn btn-sm btn-primary col-sm-3 me-2" id="createButton" (click)="onCreate()">Create</button>
        <button class="btn btn-sm btn-secondary col-sm-3" id="cancelButton" (click)="onCancel()">Close</button>
    </div>
</div>

// web-front-end/react/src/components/trade/TradeTicket/TradeTicket.tsx
import React, { useMemo, useState } from 'react';
import { Account, Stock, TradeTicket as TradeTicketModel } from '../../../models';
import './TradeTicket.css';

// SECTION 4 — Trade ticket form (rendered inside the Trade page modal).
export interface TradeTicketProps {
  stocks: Stock[];
  account?: Account;
  onCreate: (ticket: TradeTicketModel) => void;
  onCancel: () => void;
}

export const TradeTicket = ({ stocks, account, onCreate, onCancel }: TradeTicketProps) => {
  const [ticket, setTicket] = useState<TradeTicketModel>({
    quantity: 0,
    accountId: account?.id ?? 0,
    side: 'Buy',
    security: '',
  });
  const [selectedCompany, setSelectedCompany] = useState('');

  const filteredStocks = useMemo(() => {
    const query = selectedCompany.trim().toLowerCase();
    if (!query) return stocks;
    return stocks.filter((s) => s.companyName.toLowerCase().includes(query));
  }, [stocks, selectedCompany]);

  const onCompanyChange = (value: string) => {
    setSelectedCompany(value);
    const match = stocks.find((s) => s.companyName === value);
    setTicket((t) => ({ ...t, security: match ? match.ticker : '' }));
  };

  const onCreateClick = () => {
    if (!ticket.security || !ticket.quantity) {
      return;
    }
    onCreate(ticket);
  };

  return (
    <div className="p-4">
      <div className="mb-3 row">
        <label className="col-sm-2 col-form-label me-3">Account</label>
        <div className="col-sm-8">
          <input
            readOnly
            disabled
            className="form-control"
            id="accountLabel"
            value={account?.displayName ?? ''}
          />
        </div>
      </div>
      <div className="mb-3 row">
        <label className="col-sm-2 col-form-label me-3">Security</label>
        <div className="col-sm-8">
          <input
            id="stock-input"
            className="form-control"
            placeholder="Search security"
            list="stock-options"
            value={selectedCompany}
            onChange={(e) => onCompanyChange(e.target.value)}
          />
          <datalist id="stock-options">
            {filteredStocks.map((stock) => (
              <option key={stock.ticker} value={stock.companyName} />
            ))}
          </datalist>
        </div>
      </div>

      <div className="mb-3 row">
        <label className="col-sm-2 col-form-label me-3">Side</label>
        <div className="col-sm-8">
          <div className="btn-group">
            <input
              type="radio"
              className="btn-check"
              name="sideButton"
              value="Buy"
              id="buyButton"
              checked={ticket.side === 'Buy'}
              onChange={() => setTicket((t) => ({ ...t, side: 'Buy' }))}
            />
            <label
              className={ticket.side === 'Buy' ? 'btn btn-info btn-sm' : 'btn btn-secondary btn-sm'}
              htmlFor="buyButton"
            >
              Buy
            </label>

            <input
              type="radio"
              className="btn-check"
              name="sideButton"
              value="Sell"
              id="sellButton"
              checked={ticket.side === 'Sell'}
              onChange={() => setTicket((t) => ({ ...t, side: 'Sell' }))}
            />
            <label
              className={ticket.side === 'Sell' ? 'btn btn-warning btn-sm' : 'btn btn-secondary btn-sm'}
              htmlFor="sellButton"
            >
              Sell
            </label>
          </div>
        </div>
      </div>
      <div className="mb-3 row">
        <label className="col-sm-2 col-form-label me-3">Quantity</label>
        <div className="col-sm-8">
          <input
            className="form-control d-inline-block"
            id="quantityField"
            type="number"
            value={ticket.quantity}
            onChange={(e) => setTicket((t) => ({ ...t, quantity: Number(e.target.value) }))}
          />
        </div>
      </div>
      <div className="mb-3 row">
        <button className="btn btn-sm btn-primary col-sm-3 me-2" id="createButton" onClick={onCreateClick}>
          Create
        </button>
        <button className="btn btn-sm btn-secondary col-sm-3" id="cancelButton" onClick={onCancel}>
          Close
        </button>
      </div>
    </div>
  );
};
